aoscx: Fix fan RPM speeds included in environment output
ytti/oxidized pull request #2865
Opened 2023-07-12 09:04 UTC by danpoltawski

## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [x] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
Removes fan speed from Aruba CX output

Before:
```
! Fan information
! ------------------------------------------------------------------------------
! Location-      Product  Serial Number  Speed   Direction      Status  RPM
! Mbr/Slot/Fan   Name
! ------------------------------------------------------------------------------
! Tray-1/1/1     N/A      N/A            slow    front-to-back  ok      3961   
! Tray-1/1/2     N/A      N/A            slow    front-to-back  ok      3987   
! Tray-1/2/1     N/A      N/A            slow    front-to-back  ok      4016   
! Tray-1/2/2     N/A      N/A            slow    front-to-back  ok      3998   
! Tray-2/1/1     N/A      N/A            slow    front-to-back  ok      3973   
! Tray-2/1/2     N/A      N/A            slow    front-to-back  ok      3990   
! Tray-2/2/1     N/A      N/A            slow    front-to-back  ok      3996   
! Tray-2/2/2     N/A      N/A            slow    front-to-back  ok      4008   
! System-3/1/1   N/A      N/A            slow    left-to-back   ok      4024   
! System-3/1/2   N/A      N/A            slow    left-to-back   ok      13374  
! System-3/1/3   N/A      N/A            slow    left-to-back   ok      3990   
```

After:
```
! Fan information
! ------------------------------------------------------------------------------
! Location-      Product  Serial Number  Speed   Direction      Status  RPM
! Mbr/Slot/Fan   Name
! ------------------------------------------------------------------------------
! Tray-1/1/1     N/A      N/A            <speed>    front-to-back  ok      <rpm>   
! Tray-1/1/2     N/A      N/A            <speed>    front-to-back  ok      <rpm>   
! Tray-1/2/1     N/A      N/A            <speed>    front-to-back  ok      <rpm>   
! Tray-1/2/2     N/A      N/A            <speed>    front-to-back  ok      <rpm>   
! Tray-2/1/1     N/A      N/A            <speed>    front-to-back  ok      <rpm>   
! Tray-2/1/2     N/A      N/A            <speed>    front-to-back  ok      <rpm>   
! Tray-2/2/1     N/A      N/A            <speed>    front-to-back  ok      <rpm>   
! Tray-2/2/2     N/A      N/A            <speed>    front-to-back  ok      <rpm>   
! System-3/1/1   N/A      N/A            <speed>    left-to-back   ok      <rpm>   
! System-3/1/2   N/A      N/A            <speed>    left-to-back   ok      <rpm>  
! System-3/1/3   N/A      N/A            <speed>    left-to-back   ok      <rpm>   
! 
```

Closes #2864

2023-07-17 00:55 UTC, rmounce requested changes
Thanks Dan. On our 8360-24XF2C this proposed fix doesn't match all fans, and erroneously matches static power supply information. I've tested a refined regex.

Original
```
! Fan information
! ------------------------------------------------------------------------------
! Location-      Product  Serial Number  Speed   Direction      Status  RPM
! Mbr/Slot/Fan   Name
! ------------------------------------------------------------------------------
! PSU-1/1/1      N/A      N/A            slow    back-to-front  ok      6224   
! PSU-1/2/1      N/A      N/A            slow    back-to-front  ok      6240   
! Tray-1/1/1     N/A      N/A            slow    back-to-front  ok      5821   
! Tray-1/1/2     N/A      N/A            slow    back-to-front  ok      5201   
! Tray-1/2/1     N/A      N/A            slow    back-to-front  ok      5803   
! Tray-1/2/2     N/A      N/A            slow    back-to-front  ok      5093   
! Tray-1/3/1     N/A      N/A            slow    back-to-front  ok      5719   
! Tray-1/3/2     N/A      N/A            slow    back-to-front  ok      5110   
! 
! show environment power-supply
! ------------------------------------------------------------------------------
!          Product  Serial            PSU            Input   Voltage    Wattage
! Mbr/PSU  Number   Number            Status         Type    Range      Maximum
! ------------------------------------------------------------------------------
! 1/1      JL712A   CNREDACTED        OK             AC      100V-240V  550
! 1/2      JL712A   CNREDACTED        OK             AC      100V-240V  550
```

`cfg.gsub! /^((System-|Tray-)?\d+\/\S+\s+\S+\s+\S+\s+)(\S+)(\s+\S+\s+\S+\s+)\d+/, '\\1<speed>\\4<rpm>'`
```
! Fan information
! ------------------------------------------------------------------------------
! Location-      Product  Serial Number  Speed   Direction      Status  RPM
! Mbr/Slot/Fan   Name
! ------------------------------------------------------------------------------
! PSU-1/1/1      N/A      N/A            slow    back-to-front  ok      6224   
! PSU-1/2/1      N/A      N/A            slow    back-to-front  ok      6256   
! Tray-1/1/1     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/1/2     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/2/1     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/2/2     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/3/1     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/3/2     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! 
! show environment power-supply
! ------------------------------------------------------------------------------
!          Product  Serial            PSU            Input   Voltage    Wattage
! Mbr/PSU  Number   Number            Status         Type    Range      Maximum
! ------------------------------------------------------------------------------
! 1/1      JL712A   CNREDACTED        <speed>             AC      100V-240V  <rpm>
! 1/2      JL712A   CNREDACTED        <speed>             AC      100V-240V  <rpm>
```

`cfg.gsub! /^(\w+-\d+\/\S+\s+\S+\s+\S+\s+)(\S+)(\s+\S+\s+\S+\s+)\d+/, '\\1<speed>\\3<rpm>'`
```
! Fan information
! ------------------------------------------------------------------------------
! Location-      Product  Serial Number  Speed   Direction      Status  RPM
! Mbr/Slot/Fan   Name
! ------------------------------------------------------------------------------
! PSU-1/1/1      N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! PSU-1/2/1      N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/1/1     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/1/2     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/2/1     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/2/2     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/3/1     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! Tray-1/3/2     N/A      N/A            <speed>    back-to-front  ok      <rpm>   
! 
! show environment power-supply
! ------------------------------------------------------------------------------
!          Product  Serial            PSU            Input   Voltage    Wattage
! Mbr/PSU  Number   Number            Status         Type    Range      Maximum
! ------------------------------------------------------------------------------
! 1/1      JL712A   CNREDACTED        OK             AC      100V-240V  550
! 1/2      JL712A   CNREDACTED        OK             AC      100V-240V  550
```

2023-07-17 00:55 UTC, rmounce commented on lib/oxidized/model/aoscx.rb
> +    cfg.gsub! /^((System-|Tray-)?\d+\/\S+\s+\S+\s+\S+\s+)(\S+)(\s+\S+\s+\S+\s+)\d+/, '\\1<speed>\\4<rpm>'
```suggestion
    cfg.gsub! /^(\w+-\d+\/\S+\s+\S+\s+\S+\s+)(\S+)(\s+\S+\s+\S+\s+)\d+/, '\\1<speed>\\3<rpm>'
```

2023-07-17 08:26 UTC, danpoltawski commented
Ah no, but this is not matching this case:
https://github.com/ytti/oxidized/issues/2864#issuecomment-1632247001

I feel like a change of approach might be needed to match on `slow|fast` (and other 'speed' values, but I'm not sure what the entire list would be)

2023-07-17 08:28 UTC, danpoltawski commented
> I feel like a change of approach might be needed to match on `slow|fast` (and other 'speed' values, but I'm not sure what the entire list would be)

https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-7847/Content/SysHW_cmds/sho-env-fan-10.htm

2023-07-17 10:14 UTC, danpoltawski commented
@rmounce I'd be interested if this patch works for your devices too, I feel its more robust but I'm relying on the suggested values in the docs for the different fan speeds

2023-07-19 00:16 UTC, rmounce commented
@danpoltawski
Works for me. The list of fan speeds from that doc looks comprehensive, seems like a reasonable approach.

2023-07-25 09:30 UTC, merged

2023-11-13 10:17 UTC, eoli3n commented
When is the new release planned to include that fix ?